### ISSUE TITLE
grant submission creation dying when I submit invalid grant dollar amount

### ISSUE THREAD

**Issue by ywwg** [FireflyArtsCollective/ffagc#57]
```
Started POST "/grant_submissions" for 127.0.0.1 at 2017-12-08 20:44:39 -0500
Processing by GrantSubmissionsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"9h3AOLavJs25WE9Gx496yngHuYz9rv//+4Q6bVM+hOGkzNKcYzGU+RYzPav+bp+3UauHWqnFSKGDjBcsyxGieQ==", "grant_submission"=>{"name"=>"again?", "grant_id"=>"1", "requested_funding_dollars"=>"1004", "proposal"=>#<ActionDispatch::Http::UploadedFile:0x007f13b252f7e8 @tempfile=#<Tempfile:/tmp/RackMultipart20171208-22992-9nwb5u.pdf>, @original_filename="3dmark03_audit_report.pdf", @content_type="application/pdf", @headers="Content-Disposition: form-data; name=\"grant_submission[proposal]\"; filename=\"3dmark03_audit_report.pdf\"\r\nContent-Type: application/pdf\r\n">}, "commit"=>"Create Grant submission"}
  Admin Load (0.1ms)  SELECT  "admins".* FROM "admins" WHERE "admins"."id" = ? LIMIT 1  [["id", nil]]
  Artist Load (0.2ms)  SELECT  "artists".* FROM "artists" WHERE "artists"."id" = ? LIMIT 1  [["id", 3]]
  Admin Exists (0.2ms)  SELECT  1 AS one FROM "admins" LIMIT 1
   (0.1ms)  SELECT "grant_submissions".id FROM "grant_submissions" WHERE "grant_submissions"."artist_id" = ?  [["artist_id", 3]]
   (0.1ms)  begin transaction
  Grant Load (0.5ms)  SELECT  "grants".* FROM "grants" WHERE "grants"."id" = ? LIMIT 1  [["id", 1]]
   (0.1ms)  rollback transaction
Completed 500 Internal Server Error in 28ms (ActiveRecord: 1.2ms)

ActionView::MissingTemplate (Missing template grant_submissions/create, application/create with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder]}. Searched in:
  * "/home/owen/src/github/ffagc/app/views"
):
  vendor/bundle/ruby/2.3.0actionview (4.2.7.1) lib/action_view/path_set.rb:46:in `find'
  vendor/bundle/ruby/2.3.0actionview (4.2.7.1) lib/action_view/lookup_context.rb:121:in `find'
  vendor/bundle/ruby/2.3.0actionview (4.2.7.1) lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  vendor/bundle/ruby/2.3.0actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
  vendor/bundle/ruby/2.3.0actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:8:in `render'
  vendor/bundle/ruby/2.3.0actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:46:in `render_template'
  vendor/bundle/ruby/2.3.0actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:27:in `render'
  vendor/bundle/ruby/2.3.0actionview (4.2.7.1) lib/action_view/rendering.rb:100:in `_render_template'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  vendor/bundle/ruby/2.3.0actionview (4.2.7.1) lib/action_view/rendering.rb:83:in `render_to_body'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/abstract_controller/rendering.rb:25:in `render'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:16:in `render'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  vendor/bundle/ruby/2.3.0activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/abstract_controller/base.rb:198:in `process_action'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in `call'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.3.0activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
  vendor/bundle/ruby/2.3.0actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/conditionalget.rb:38:in `call'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.3.0activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.3.0activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.3.0activerecord (4.2.7.1) lib/active_record/migration.rb:377:in `call'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.3.0railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.3.0railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.3.0railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.3.0activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/lock.rb:17:in `call'
  vendor/bundle/ruby/2.3.0actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.3.0railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.3.0railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/lock.rb:17:in `call'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  vendor/bundle/ruby/2.3.0rack (1.6.5) lib/rack/handler/webrick.rb:88:in `service'
  /usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'


  Rendered vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (18.9ms)
  Rendered vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.7ms)
  Rendered vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.4ms)
  Rendered vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/templates/rescues/missing_template.html.erb within rescues/layout (36.8ms)


```

**Comment by ywwg** [comment]
don't know why it can't find "create" when it's definitely there.

**Comment by ywwg** [comment]
oh I was looking at the wrong controller.  Indeed, the failure case was missing
